### ISSUE TITLE
Nothing to report, just want to say: THIS IS GORGEOUS! 😆

### ISSUE THREAD

**Issue by flyinghawker** [imnapo/react-native-cn-richtext-editor#15]

**Comment by jsamr** [comment]
@imnapo  I wanted to thank you also ; this library was a missing spot in RN ecosystem for years!!

**Comment by himanshupadia** [comment]
@flyinghawker could you please help me get value from editer with HTML tags so I can sent it to db with same? I am stuck add looking for solution from last 2 days. Please help me.
appreciating your help, because of this only I got stuck. 
**Input String:** This is **bold** and _italic_ text
**output should be something like this or in format of editor:** 
`<div><p><span>This is </span><span style="font-weight: bold;">bold</span><span> and </span><span style="font-style: italic;">italic </span><span>text</span></p></div>`
