### ISSUE TITLE
HTML tags input

### ISSUE THREAD

**Issue by michaelVictoriaDev** [imnapo/react-native-cn-richtext-editor#17]
Is this repo still on going? well I want to know if you handle HTML tags. And I see there's **convertToHtmlString** and **convertToObject** i don'at know if this two handle html tags. Could you help me or show me how to use it ?

**Comment by ohpax** [comment]
Yes, we are actively working on this repo,  We are converting our text to an object and the object to HTML and you can use that to convert between HTML and the object, back and forth. But we define what HTML tags or CSS classes we support so that is a limited function and it only workes for the stuff which is created by this tool. But, we can always add new stuff to support.

**Comment by michaelVictoriaDev** [comment]
@ohpax Thanks for replying on this, Question on **convertToHtmlString** and **convertToObject**
		`let value = [getInitialObject()];`
is this the right way to use it `let htmlToString = convertToHtmlString(value)`  this will convert html string and  **let toObject = convertToObject(htmlToString)** and to transform back to object ?

Coz I assumed that the editor is handle the object type ? :)

**Comment by ohpax** [comment]
The way you use the code it is correct, but you can not pass it any HTML. The only HTML code which this function can convert is the one which is generated by our generator. So, the answer to your second question is no, you can not pass any HTML and expect to have it styled correctly in the editor.

**Comment by mqtik** [comment]
I'm sanitizing all HTML, even removing all tags.
It wont work..

I'm making a few changes to see what I come up with..

**Comment by mqtik** [comment]
Already made a pull request
